- hosts: workers
  user: cloud_user
  become: yes
  vars:
    repo_url: https://github.com/sbizinov/test_task.git
    project_path: /tmp/build/
  tasks:
    - name: "Installing Docker and NPM for local build"
      yum:
        name: "{{ item }}"
        state: latest
      with_items:
        - yum-utils
        - device-mapper-persistent-data
        - lvm2
        - npm
        - git
        - python-docker-py
    - name: "Configuring docker-ce repo"
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
        mode: 0644
    - name: " Installing Docker"
      yum:
        name: docker-ce
        state: present
    - name: " Starting and Enabling Docker service"
      service:
        name: docker
        state: started
        enabled: yes
    - name: Clone a github repository
      git:
        repo: "{{ repo_url }}"
        dest: "{{ project_path }}"
        clone: yes
        update: yes
    - name: Build the app.
      npm:
        path: "{{ project_path }}task_1/src"
        state: present
    - name: Build a docker image
      docker_image:
        name: test_img:v1
        source: build
        build:
          path: "{{ project_path }}/task_1"
        state: present
      tags:
        - build
    - name: Run docker image.
      docker_container:
        name: test
        image: test_img:v1
        state: started
        ports:
          - "80:8080"
      tags:
        - run
