version: '3'
services:
    nginx:
        build: ./images/nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./www:/var/www
    php:
        build: ./images/php
        volumes:
            - ./www:/var/www
    mysql:
        image: mysql:8.0
        ports:
            - "3306:3306"
        volumes:
         - ./database:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: onlineshop
